import { HeaderComponent } from "@/components/Header";
import { CartProviderComponent } from "@/provider/CartProvider";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="select-none">
        <CartProviderComponent>
          <Toaster position="top-center" />
          <HeaderComponent />
          <>{children}</>
        </CartProviderComponent>
      </body>
    </html>
  );
}
